### ISSUE TITLE
[$50] Browser doesn't remember the username when 'remember me' is checked.

### ISSUE THREAD

**Issue by macs054** [appirio-tech/arena-web#505]
Issue for regression tests:
[a4350000000CwOBAA0] Web Arena : To verify 'remember me' remembers the username when user starts typing the matching chars
[a4350000000DDAlAAO] To verify browser remembers the username entered by user is 'remember me' is checked

Steps:
For [a4350000000CwOBAA0]
1. Go to https://arena.topcoder.com
2. Enter username and password
3. Check 'Remember Me' and click 'Login'
4. When logged-in click Logout link then close the browser/tab.
5. Open the above arena URL in a new tab/window.
6. Start typing the username.

Expected result:
Arena should remember the matching username.

Actual result:
Arena does not remember the username when the user starts typing.

Steps:
For [a4350000000DDAlAAO] To verify browser remembers the username entered by user is 'remember me' is checked
1. Hit url : arena.topcoder.com
2. Enter the username and password
3. Click login
4. Now logout of the system and close the browser
5. Reopen the browser and type the username 
6. Now enter the username and password, check the 'remember me' and click login
7. Now logout of the system and close the browser
8. Reopen the browser and type the username

Expected result:
The browser should remember the username

Actual result:
The browser doesn't remember the username.

Note:
*When 'Remember Me' is checked and when the user logs out, the browser remembers the username. But when the browser was restarted it doesn't remember the username even when the user starts typing.

Video:
http://youtu.be/VXeaO2Jj4iA

Environment:
Windows 7 32-bit , Chrome 40.0.2214.91

**Comment by ananthhh** [comment]
In all application, Remember Me used to retain logged in state of user.
For ex, if user logged in to the app and if user closed the browser without logout, then when user visits the web arena again using same browser then user will be directly taken to dashboard instead of login page.

Use cases mentioned in the bug is not correct. This functionality is there in browser. When user login to web arena, browser will ask the user to remember username or not. If he select yes, then browser will remember that.

Please check Remember Me functionality in other websites like google, yahoo and so on
As per current implementation, Remember Me is implemented in correct way in web arena. So there is no fix required

**Comment by huangqun** [comment]
@ananthhh you are right, this is invalid use case.
