### ISSUE TITLE
python indentation error

### ISSUE THREAD

**Issue by Sea-Snell** [appirio-tech/arena-web#507]
I get errors on the indentation of my python code even when I know it is correct.

**Comment by skyhit** [comment]
can you provide some screenshot and reproduce steps?

**Comment by Sea-Snell** [comment]
my code:
![code](https://cloud.githubusercontent.com/assets/6655321/5895283/54fa43d4-a4e0-11e4-9d46-ce93c8a3347e.png)

the error:
![error](https://cloud.githubusercontent.com/assets/6655321/5895284/5ebf8d20-a4e0-11e4-8583-af70e7cf4f0c.png)

**Comment by Sea-Snell** [comment]
the error occurs when I compile the code.

**Comment by skyhit** [comment]
can you provide the code text, I tried in my env, python is working.

**Comment by Sea-Snell** [comment]
I noticed that this error only occurred on two out of the three problems that I did.

here is the code text:
```Python
class Substitute:
	def getValue(self, key, code):
        value = ""
		for i in code:
			for x in range(len(key)):
               	if i == key[x]:
                   	if x == 9:
                    	value += "0"
                    else:
                        value += str(x + 1)
   	    return int(value)
```

**Comment by Sea-Snell** [comment]
That code is from the problem named Substitute.

**Comment by Braceface** [comment]
I had a huge issue with this during SRM 655 this morning (4/9/15).  I basically had to guess and check as to what the compiler wanted my code to look like in order to get it to work.  It was quite wonky.  There were some lines I had to tab 2 or 3 times past the above line in order for it to work.  One of my statements had to look like this in order to compile/execute.

```
If this and that and that or that:
        print(this)
    return "Impossible"
```

I am unable to paste any of the code because I didn't submit.  This was my first SRM and I thought we got to continue working on code after the intermission.  I just did a practice problem and it worked great.

**Comment by mariehoffmann** [comment]
Hi, 
I have the same problem in the Arena. When hitting the return button at the end of a line the indentation is generated by single spaces instead of tabs. Hence, I get errors like "indentation level does not match". So far I remove and replace them manually to get the code compiled, which is time-consuming and annoying. Whereas the editor in ContestAppletProd.jnlp works fine!

(Firefox 41.0.2, Mac OS X 10.9.5)

**Comment by j-a-b** [comment]
Hi @skyhit, you asked for reproduction instructions on this issue quite some time ago. I believe have identified and logged (#710) what seems to be the root cause of this issue with enough info to consistently reproduce it

This bug makes python coding in the web arena extremely cumbersome unless you're aware of the root issue and how to work around it. I hope help speed its resolution!

I believe @mariehoffmann is pointing out the same underlying issue in her comment above.
